"""
Django settings for backback project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
from rest_framework.renderers import JSONRenderer
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-l7ir1rwi@_riq6&dmq#x#62_55^f0mmh+p28h6@ft_geeax3l1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'dj_rest_auth',
    'api',
    'allauth',
    'allauth.account',
    #'allauth.socialaccount',
    'dj_rest_auth.registration',
    'twilio',
    #'notification',
    'django_otp',
    'django_otp.plugins.otp_totp',
    
    
]
AUTH_USER_MODEL="api.User"
#ACCOUNT_AUTHENTICATION_METHOD = 'email'
#ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
#ACCOUNT_USERNAME_REQUIRED = False
#ACCOUNT_USER_MODEL_USERNAME_FIELD = 'email'
#USERNAME_REQUIRED= False 
#ACCOUNT_EMAIL_VERIFICATION = None
#ACCOUNT_CONFIRM_EMAIL_ON_GET = False
#ACCOUNT_USER_MODEL_USERNAME_FIELD=None

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backendetaxi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backendetaxi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTHENTIFICATION_BACKENDS = ['api.models.EmailBackend']
REST_FRAMEWORK={
    "DEFAULT_AUTHENTIFICATION_CLASSES":
         'rest_framework.authentification.TokenAuthentification'

}
REST_AUTH_SERIALISERS={
     "LOGIN_SERIALIZERS":"api.serializers.NewLoginSerializer",
}
REST_AUTH_SERIALISERS={
    "REGISTER_SERIALIZERS":"api.serializers.NewRegistrationSerializer",

    "DRIVER_REGISTRATION_SERIALIZER":"api.serializers.DriverRegistrationSerializer",  
}
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
}
#TWILIO_ACCOUNT_SID = 'your_account_sid'
#TWILIO_AUTH_TOKEN = 'your_auth_token'
#TWILIO_FROM_NUMBER = 'your_twilio_phone_number'
#otp-verification
OTP_TOTP_ISSUER = 'api'
#OTP_TOTP_ISSUER = 'My App'
OTP_TOTP_DIGITS = 6
OTP_TOTP_INTERVAL = 120
OTP_TOTP_ALGORITHM = 'sha256'
OTP_TOTP_SECRET_SIZE = 20
OTP_TOTP_THROTTLE_FACTOR = 1
OTP_THROTTLE_FACTOR = 1
#otp-verification